.github/workflows/mkdocs_build.yml
=> ci: build automation for documentation

.github/workflows/docker-image.yml, .github/workflows/node.js.yml
=> ci: add build automation w/ github actions

docs/overrides/partials/footer.html, mkdocs.yml
=> docs: remove prev/next guidance

package-lock.json, package.json, webui/package-lock.json, webui/package.json
=> build(deps): update jest to 26.6.0

src/models/ISecretManagerService.ts, src/utils/SecretManagerService.ts, src/utils/vaultDbProvider.ts, webui/src/components/app/app.js, webui/src/components/pages/index.js, webui/src/components/pages/networkconfigs/networkconfigs.container.js, webui/src/components/pages/networkconfigs/networkconfigs.js, webui/src/components/pages/networkconfigs/networkconfigs.test.js
=> refactor: migrate from internal

.github/workflows/docker-image.yml
=> ci: update docker build

.github/workflows/docker-image-ci.yml, .github/workflows/docker-image.yml
=> ci: add docker ci

src/amt_libraries/amt.js, swagger.yaml
Following changes in this PR:
- Updated descriptions for all API
- Added missing Schemas
- Updated examples for most API
- Fixed a spelling issue in amt.js
=> docs(swagger): updated swagger docs for 1.3

README.md
@rsdmike What's the minimum steps required for this?  Do we even need steps to update .mpsrc?
=> docs(readme): update to v1.4.0

src/db/device.ts, src/models/Config.d.ts, src/routes/devices/deviceValidator.ts, src/routes/devices/getAll.ts, src/routes/devices/index.ts, src/test/collections/MPS.postman_collection.json, src/utils/constants.ts
closes [AB#2935](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/2935)
=> feat(api): add pagination following odata spec

src/index.ts
resolves #288
Co-authored-by: lobando
=> fix(startup): mps now starts with tls_offload set to true

.mpsrc
Related work items: [AB#3417](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3417)
=> refactor(sslpostgres): removed password and enabled ssl

src/routes/certs/index.ts
=> fix(api): cert now pulls from config instead of disk

src/mpsMicroservice.ts
closes [AB#3633](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/3633)
=> feat(telemetry): add events for CIRA Disconnect/Connection

src/test/collections/MPS.postman_collection.json
=> fix(api): updated version api test uri

package-lock.json, package.json
=> build(version): bump to v2.1.0

src/Healthcheck.ts, src/amt/test/amt.test.ts, src/amt/test/ips.test.ts, src/amt/test/wsman.test.ts, src/data/postgres/index.ts, src/interfaces/ISecretManagerService.ts, src/models/models.ts, src/routes/health/get.ts, src/routes/health/index.ts, src/routes/index.ts, src/test/helper/jest.ts, src/test/mpsservertest.test.ts, src/test/mqtt.test.ts, src/test/routes/healthcheck.spec.ts, src/utils/SecretManagerService.ts
closes [AB#4076](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4076)
=> feat(healthcheck): adds API endpoint for healthcheck

src/data/postgres/tables/device.ts, src/index.ts, src/test/device.test.ts, src/test/postgresDb.test.ts
Added unit tests for database(postgres) interactions
=> fix(test): added unit test for db(pg)

Jenkinsfile
Notifies the provided slack channel on internal scan failures
=> ci: notify slack on scan failures

.github/workflows/node.js.yml, .gitignore, jest.config.js, package-lock.json, package.json
=> ci(tests): add test output

src/amt/CIRAHandler.ts
=> fix(cira): handle chunked http message

src/amt/AMT.ts, src/amt/CIRAHandler.ts, src/amt/ConnectedDevice.ts, src/amt/enums/amt_enums.ts, src/amt/models/amt_models.ts, src/routes/amt/powerCapabilities.test.ts, src/routes/amt/powerCapabilities.ts
closes [AB#4553](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4553)
=> refactor(power): use new device handling

src/amt/ConnectedDevice.ts, src/amt/connectedDevice.test.ts, src/amt/models/amt_models.ts, src/routes/amt/auditLog.test.ts, src/routes/amt/auditLog.ts, src/test/helper/wsmanResponses.ts
refactor(api): updates audit log and adds unit tests for it to connected devices
closes [AB#4551](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4551)
=> refactor(api): updates audit log and adds unit tests for it to connected devices

src/amt/models/common.ts, src/routes/amt/auditLog.ts
closes [AB#4551](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4551)
=> fix(api): reverts auditlog field names back to being capitalized

package-lock.json, package.json
closes: [AB#4562](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4562)
=> build(deps): add @open-amt-cloud-toolkit/wsman-messages

src/amt/ConnectedDevice.ts, src/amt/connectedDevice.test.ts, src/amt/models/amt_models.ts, src/amt/models/cim_models.ts, src/amt/models/common.ts, src/amt/models/ips_models.ts, src/routes/amt/getAMTFeatures.test.ts, src/routes/amt/getAMTFeatures.ts, src/routes/amt/setAMTFeatures.ts, src/utils/constants.ts
=> refactor(api): update getAMTFeatures to use new CIRA connections 

src/amt/ConnectedDevice.ts, src/amt/connectedDevice.test.ts, src/routes/amt/eventLog.ts, src/routes/amt/getVersion.test.ts, src/routes/amt/getVersion.ts, src/routes/amt/powerCapabilities.test.ts, src/routes/amt/powerCapabilities.ts, src/routes/amt/userConsent/cancel.test.ts, src/routes/amt/userConsent/cancel.ts, src/routes/amt/userConsent/request.ts, src/routes/amt/userConsent/send.ts, src/test/helper/wsmanResponses.ts
=> fix(api): updated return value code with value type

src/routes/devices/getAll.test.ts, src/routes/devices/getAll.ts
=> fix(api): connection status query parameter now matches API docs for devices

jest.config.js
=> test(config): consider all files for test coverage

src/routes/health/get.test.ts, src/routes/health/index.test.ts
=> test: Adding unit test to health

src/routes/certs/index.test.ts
Adding unit test to routes/cert folder
Just adding unit test
=> test(cert): Adding unit test to cert folder

src/routes/index.test.ts
Adding simple unit test to index.ts
[AB#5549](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5549)
Adding simple unit test to index.ts
Adding unit test
n/a
=> test(routes): Adding unit test to index

src/routes/devices/create.test.ts, src/routes/devices/delete.test.ts, src/routes/devices/disconnect.test.ts, src/routes/devices/disconnect.ts, src/routes/devices/get.test.ts, src/routes/devices/index.ts, src/routes/devices/stats.test.ts, src/routes/devices/tags.test.ts, src/routes/devices/update.test.ts
closes [AB#5499](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5499)
=> test: adds unit tests for devices

src/utils/parseEnvValue.test.ts
Adding unit testing to utils/parseEnvValue.ts
[AB#5550](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5550)
Adding unit testing
Just unit testing
n/a
=> test(utils): Adding parseEnvValue unit test

src/routes/devices/index.test.ts
Adding unit test file to devices/index.ts
[AB#5500](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5500)
Adding unit test to index.ts file under devices
Adding unit testing
n/a
=> test(devices): Add unit test to index

src/routes/auth/authValidator.test.ts, src/routes/auth/login.test.ts
Adding new files for unit testing auth content.
Covering login.ts and authValidator.ts
[AB#5503](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5503)
=> test(auth): Adding unit test to auth folder

src/utils/tlsConfiguration.test.ts, src/utils/tlsConfiguration.ts
closes [AB#5552](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5552)
=> test(utils): adds tests for tlsConfiguration

jest.config.js
=> test(coverage): remove test directory from coverage

src/factories/DbCreatorFactory.test.ts
Adding new files for unit testing factories content
[AB#5589](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5589)
Adding unit test to factories folder
Just adding unit test
n/a
=> test(factories): Adding unit test to factories

src/amt/CIRAChannel.test.ts, src/amt/CIRAChannel.ts, src/amt/CIRAHandler.test.ts, src/amt/CIRAHandler.ts, src/amt/httpHandler.test.ts, src/utils/parseWSManResponseBody.test.ts, src/utils/parseWSManResponseBody.ts
[AB#4461](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/4461)
=> test(cira): added unit test for CIRAHandler

src/utils/certificates.test.ts
closes [AB#5501](https://dev.azure.com/rbheBoards/c7d9d701-a85f-45ff-91f6-26c56ff2c4de/_workitems/edit/5501)
=> test(utils): adds tests for certificates

src/server/webserver.test.ts, src/server/webserver.ts
=> fix(cira): close cira channel after request

src/server/mpsserver.ts
Fix CIRA connection race condition
Configure 30sec keepalive time for all incoming CIRA connections
=> fix: CIRA connection race condition and add 30 sec keepalive time

src/routes/index.test.ts, src/server/mpsserver.ts, src/server/mpsservertest.test.ts, src/server/webserver.test.ts
=> test(mpsserver): increase code coverage for MPS

package-lock.json, package.json, src/amt/CIRAHandler.ts, src/amt/DeviceAction.ts, src/amt/HttpHandler.ts, src/amt/httpHandler.test.ts, src/routes/amt/auditLog.ts, src/routes/amt/bootOptions.test.ts, src/routes/amt/bootOptions.ts, src/routes/amt/eventLog.ts, src/routes/amt/getAMTFeatures.ts, src/routes/amt/powerAction.test.ts, src/routes/amt/powerAction.ts, src/routes/amt/setAMTFeatures.test.ts, src/routes/amt/setAMTFeatures.ts
=> build(deps): fix wsman-messages version

src/amt/CIRAHandler.ts, src/server/webserver.ts
=> refactor(amt): limit connect retry attempts for invalid password

src/routes/amt/bootOptions.test.ts, src/routes/amt/bootOptions.ts
=> refactor(power): ensure AMT response aligns with v2.1

Dockerfile, README.md
=> fix(dockerfile): set user as non-root

src/amt/HttpHandler.ts
=> fix(nonce): set nonce to 8 character hexadecimal

src/routes/health/get.test.ts, src/routes/health/get.ts, src/utils/constants.ts
=> refactor(healthcheck): improves testability and code coverage

.mpsrc, src/models/Config.d.ts, src/routes/auth/authorizeDevice.test.ts, src/routes/auth/authorizeDevice.ts, src/routes/auth/index.ts, src/routes/auth/login.ts, src/routes/auth/signature.ts, src/routes/index.test.ts, src/routes/index.ts, src/test/collections/MPS.postman_collection.json, src/test/helper/config.ts
=> feat(api): to get short lived bearer token for direction sessions

src/data/postgres/tables/device.test.ts
=> test(db): refactor initialization for unit tests

.github/workflows/node.js.yml
=> ci: remove node 12 and add 18 for build

.github/workflows/api-test.yml, src/test/collections/data/mps_security_api_test_data.json, src/test/collections/mps_security_api_test_postman_collection.json
This PR creates the setup for the following tasks:
https://dev.azure.com/rbheBoards/OpenAMT/_workitems/edit/7422/?workitem=11843
https://dev.azure.com/rbheBoards/OpenAMT/_workitems/edit/7420/?workitem=11845
https://dev.azure.com/rbheBoards/OpenAMT/_workitems/edit/7415/?workitem=11841
https://dev.azure.com/rbheBoards/OpenAMT/_workitems/edit/7415/?workitem=11839
=> test(api): added postman verbs data tests

.github/workflows/api-test.yml, .github/workflows/codeql-analysis.yml
=> ci(postman): upload postman results as build artifact

.github/workflows/node.js.yml
=> ci(jest): upload junit results as built artifact

.github/workflows/api-test.yml, .github/workflows/node.js.yml
=> ci: rename test file output

package-lock.json, src/routes/amt/powerAction.ts, src/routes/amt/powerCapabilities.ts
fixes: Strange compilation errors #657
=> fix: powerAction and powerCapabilites now transpile without errors

CHANGELOG.md, package-lock.json, package.json
=> docs: updates changelog to v2.5.0

src/amt/CIRAHandler.ts, src/data/postgres/tables/device.ts, src/routes/amt/auditLog.ts, src/routes/devices/stats.ts, src/routes/health/get.ts, src/routes/index.ts, src/routes/version/get.test.ts, src/routes/version/get.ts, src/routes/version/index.test.ts, src/routes/version/index.ts, src/test/collections/MPS.postman_collection.json, src/utils/amtHelper.ts, src/utils/constants.ts
Adds version api endpoint to mps.  Returns serviceVersion
=> feat(serviceVersion): adds version api endpoint

src/data/postgres/tables/device.test.ts, src/data/postgres/tables/device.ts, src/interfaces/IDeviceTable.ts, src/logging/messages.ts, src/routes/devices/stats.test.ts, src/routes/devices/stats.ts, src/server/mpsservertest.test.ts
=> fix(api): remove hard limit of 25 from stats route

src/middleware/validate.test.ts, src/routes/devices/stats.test.ts
=> test: enhance unit test coverage for middleware and stats

.github/workflows/projectsSync.yaml
=> ci: add projects sync to mps

.github/workflows/azureBoardsSync.yaml
=> ci: add azure boards sync

src/amt/HttpHandler.ts, src/amt/httpHandler.test.ts
=> fix(auth): handle qop="auth-int, auth" header

src/utils/redirectInterceptor.test.ts, src/utils/redirectInterceptor.ts
=> fix(redirection): ensure nonce is used correctly

src/routes/amt/getHardwareInfo.ts
closes Copy/paste error in src/routes/amt/getHardwareInfo.ts #655
=> fix(api): getHardwareInfo pulls correct status for CIM_PhysicalMemory

package-lock.json, package.json, src/amt/CIRAHandler.ts, src/amt/ConnectedDevice.ts, src/middleware/cira.ts
=> refactor(cira): increases stability of calls to a device

src/factories/DbCreatorFactory.test.ts, src/factories/DbCreatorFactory.ts, src/factories/SecretManagerCreatorFactory.test.ts, src/factories/SecretManagerCreatorFactory.ts
=> fix(db): ensures dbInstance is a singleton

.github/workflows/api-test.yml, .github/workflows/changelog.yml, .github/workflows/codeql-analysis.yml, .github/workflows/docker-image-ci.yml, .github/workflows/docker-image.yml, .github/workflows/node.js.yml, .github/workflows/semantic.yml
=> ci: update checkout to v3, update semantic pr checks

.github/workflows/node.js.yml
=> ci: add manual dispatch

data/initMPS.sql, src/data/postgres/tables/device.test.ts, src/data/postgres/tables/device.ts, src/models/models.ts, src/routes/devices/create.test.ts, src/routes/devices/create.ts, src/test/collections/MPS.postman_collection.json
=> feat(db): maintenance sync hostname information

CHANGELOG.md, package-lock.json, package.json
=> build: update to v2.7.0, update changelog

src/server/webserver.test.ts, src/server/webserver.ts
=> fix(api): ensure middleware is loaded from correct directory

src/amt/ConnectedDevice.ts, src/amt/connectedDevice.test.ts, src/custom.d.ts, src/data/postgres/tables/device.test.ts, src/data/postgres/tables/device.ts, src/middleware/custom/example.ts, src/models/Config.d.ts, src/routes/devices/create.test.ts, src/routes/devices/create.ts, src/routes/devices/delete.ts, src/routes/devices/get.test.ts, src/routes/devices/get.ts, src/routes/devices/getAll.test.ts, src/routes/devices/getAll.ts, src/routes/devices/stats.ts, src/routes/devices/tags.ts, src/routes/devices/update.ts, src/server/mpsserver.ts, src/server/webserver.ts, src/test/collections/MPS.postman_collection.json, src/test/helper/config.ts, src/utils/wsRedirect.test.ts
open-amt-cloud-toolkit/rps#795
=> feat: enhance multitenancy support

CHANGELOG.md, package.json
=> build: update to v2.8.0, update changelog

src/index.ts, src/secrets/vault/index.test.ts, src/secrets/vault/index.ts
Fix issue https://github.com/open-amt-cloud-toolkit/open-amt-cloud-toolkit/issues/164
=> fix(health): fix vault health check failure when in HA mode

src/interfaces/ISecretManagerService.ts, src/server/mpsservertest.test.ts, src/server/webserver.test.ts, src/utils/certificates.test.ts, src/utils/certificates.ts, src/utils/wsRedirect.test.ts
=> fix: upated IsecretManagerService

CHANGELOG.md, package-lock.json, package.json
=> build: update to v2.8.1, update changelog

src/server/webserver.ts
Ensure test files are excluded as being considered as middleware targets
=> fix: exclude test.js files from custom middleware

src/routes/amt/deactivate.ts
=> fix: add missing tenantid in deactivate call

CHANGELOG.md, package-lock.json, package.json
=> build: update package.json and changelog to v2.8.2

Dockerfile
=> build(docker): ensure healthcheck remains in same location

.github/workflows/node.js.yml
=> ci(deps): bump codecov to 3.1.3

CHANGELOG.md, package-lock.json, package.json
=> build: update changelog and version to v2.8.3

CHANGELOG.md, package-lock.json, package.json
=> build: update changelog and version to v2.8.4

CHANGELOG.md, package-lock.json, package.json
=> build: update changelog and version to v2.9.0

Dockerfile
=> build(docker): ensure packages are up-to-date in alpine image

CHANGELOG.md, package-lock.json, package.json
=> build: update version and changelog to v2.9.1

src/data/postgres/tables/device.test.ts, src/data/postgres/tables/device.ts, src/interfaces/IDeviceTable.ts, src/routes/devices/create.test.ts, src/routes/devices/create.ts, src/routes/devices/deviceValidator.ts, src/routes/devices/get.test.ts, src/routes/devices/getAll.test.ts, src/routes/devices/getAll.ts, src/server/mpsservertest.test.ts, src/test/collections/MPS.postman_collection.json
=> feat: support device friendly name

CHANGELOG.md, package-lock.json, package.json
=> build: update version and changelog to v2.10.0

src/middleware/custom/example.ts, src/routes/devices/get.ts, src/test/collections/MPS.postman_collection.json
get device should return on authenticated matching tenant
=> fix: default tenantId is now blank

.github/workflows/node.js.yml
=> ci: remove node 14 from build, adds node 20

CHANGELOG.md, package-lock.json, package.json
=> build: updates package.json and changelog to v2.10.1

docker-compose.yml
=> build: update vault to hashicorp vault

docker-compose.yml
=> refactor: unpin docker compose minor revision

releaserc.json
=> ci: update plugins for semantic release

.snyk, README.md
=> docs: update badges

src/routes/devices/getAll.ts
=> refactor(api): removes use of 'any' type for $top and $skip

.github/workflows/release.yml, releaserc.json
=> ci: add release tag to docker image

.releaserc.json
=> ci: rename releaserc.json to .releaserc.json

src/server/webserver.test.ts, src/server/webserver.ts
=> fix: redirection token expiration and device UUID check

.releaserc.json
=> ci: updated automated docker push on release

src/test/collections/MPS.postman_collection.json
=> test: add dnssuffix to api tests

CHANGELOG.md, package-lock.json, package.json, src/routes/amt/bootOptions.ts
=> fix: boot order for IDER

.github/workflows/codeql-analysis.yml
=> ci: adds report out to code analysis action

.github/workflows/release.yml
=> ci: adds persist-credentials:false to checkout

.eslintrc.json
=> fix: updates lint rules to remove unbound method check

package-lock.json, package.json
=> fix: update build tasks, package.json and changelog

CHANGELOG.md, package-lock.json, package.json
=> fix: update changelog

.releaserc.json
=> ci: automatically update package.json version during release process

package-lock.json, package.json, src/amt/ConnectedDevice.ts, src/models/Config.d.ts, src/routes/devices/getRedirStatus.test.ts, src/routes/devices/getRedirStatus.ts, src/routes/devices/index.ts, src/server/webserver.test.ts, src/server/webserver.ts, src/test/collections/MPS.postman_collection.json, src/utils/wsRedirect.test.ts, src/utils/wsRedirect.ts
=> fix: update redirect to handle multiple connections

.github/workflows/trivy-scan.yml
=> ci: add trivy results to github security tab

src/amt/DeviceAction.ts, src/routes/amt/setAMTFeatures.ts, src/routes/health/get.test.ts, src/server/mpsserver.ts, src/server/webserver.ts, src/utils/wsRedirect.ts
=> fix: remove unnecessary console.log statements

src/routes/auth/authValidator.ts, src/test/collections/MPS.postman_collection.json
=> fix: update user name validation

src/routes/devices/deviceValidator.ts, src/test/collections/MPS.postman_collection.json
=> fix: adds hostname length check

package-lock.json, package.json
=> build(deps-dev): update typescript to 5 and jest to 29

src/models/Config.d.ts, src/utils/tlsConfiguration.test.ts, src/utils/tlsConfiguration.ts
=> refactor: remove direct tls loading

.github/workflows/node.js.yml
=> ci: remove node 16 from build

src/routes/devices/deviceValidator.ts
=> fix: adds validation for tag array types

Dockerfile
=> fix: expose only 3000 and 4433, and update docker file

.github/workflows/trivy-scan.yml
=> ci: address permissions for trivy-scan to upload

README.md
=> docs: update badge style

.gitignore, .vscode/launch.json
=> build: allow launch settings for DX

.github/workflows/semantic.yml
=> ci: add top level permissions to semantic.yml

.github/workflows/node.js.yml
=> ci: add top level permissions for nodejs.yml

package-lock.json, package.json
=> build(deps): update express to 4.21.0

src/utils/wsRedirect.test.ts, src/utils/wsRedirect.ts
=> fix: browser data when cira channel is closed

src/server/webserver.ts
=> refactor: adjust types for websockets

Dockerfile
=> build(docker): set image to node-lts

.devcontainer/devcontainer.json, README.md
- [ N/A ] Unit Tests have been added for new changes
- [ N/A ] API tests have been updated if applicable
- [ N/A ] All commented code has been removed
- [ N/A ] If you've added a dependency, you've ensured license is compatible with Apache 2.0 and clearly outlined the added dependency.
Add support for devcontainer in vscode.
Feature device-management-toolkit/cloud-deployment#383
=> feat(docker): add support for devcontainer

.github/workflows/docker-image.yml, .github/workflows/release.yml, .releaserc.json
=> feat(docker): enable multiarch build

.releaserc.json
=> ci: fix dockerx build

src/routes/auth/authorizeDevice.ts, src/routes/auth/login.ts, src/routes/auth/signature.ts, src/server/webserver.test.ts
=> fix: grab req.tenantId for device token

src/models/models.ts, src/routes/amt/amtFeatureValidator.ts, src/routes/amt/getAMTFeatures.test.ts, src/routes/amt/getAMTFeatures.ts, src/routes/amt/setAMTFeatures.test.ts, src/routes/amt/setAMTFeatures.ts
=> fix: adds HTTP, WinRE and PBA to OCR status

.mpsrc, src/amt/APFProcessor.test.ts, src/amt/APFProcessor.ts, src/amt/CIRAChannel.test.ts, src/amt/CIRAChannel.ts, src/amt/CIRAHandler.test.ts, src/index.ts, src/models/Config.d.ts, src/server/mpsserver.ts, src/test/helper/config.ts, src/utils/constants.ts
- Increased default window from 32KB to 80KB for better throughput
- Minor code cleanups
=> perf(cira): bump default window size to 80KB
